### ISSUE TITLE
Game become unplayable after tapping a number 2 times

### ISSUE THREAD

**Issue by YouKnow-sys** [storopoli/sudoku#8]
If we choose a place in the grid and select a number **two times back to back** and then click the undo button game will get bugged and we no longer will be able to play.
As you can see I'm selecting another spot but I can't enter anything in it.
![Screenshot_2024-01-26-19-06-49-928_com.android.chrome.png](https://github.com/storopoli/sudoku/assets/17937017/356ce3cc-1976-414d-8689-a65ede3987fe)

**Comment by storopoli** [comment]
Should be fixed now
